# Generated by Django 6.0.3 on 2026-04-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='generation_status',
            field=models.CharField(default='NOT_STARTED', max_length=64),
        ),
        migrations.AddField(
            model_name='song',
            name='task_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
